name: Commit scheduler
on:
    schedule:
      - cron: '0 6 * * 1'

jobs:
  build:
    name: Release image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Dist directory
        run: mkdir img-dist
      - name: Build Alpine armhf
        env:
          ALPINE_MIRROR: http://dl-cdn.alpinelinux.org/alpine
          ARCH: armhf
        run: |
          echo "ARCH=armhf" >> $GITHUB_ENV
          ./docker-runner
          sudo mv dist/*img.gz img-dist
      - name: Build Alpine aarch64
        env:
          ALPINE_MIRROR: http://dl-cdn.alpinelinux.org/alpine
          ARCH: aarch64
        run: |
          echo "ARCH=aarch64" >> $GITHUB_ENV
          ./docker-runner
          sudo mv dist/*img.gz img-dist
      - name: Create environment variables
        run: |
          echo ::set-env name=RELEASE_TAG::"$(date +%Y_%m_%d_%H_%m)"
          echo ::set-env name=RELEASE_NAME::"Refresh of $(date +'%Y-%m-%d')"
      - name: Publish release
        uses: meeDamian/github-release@1.0
        with:
          gzip: folders
          files: img-dist/
          token: ${{ secrets.GITHUB_TOKEN }}
